import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Inputs that determine what the deployed site actually is. `scripts` is
 * included so the attestation covers the tooling that produces it, not just
 * the content it vouches for.
 */
export const INCLUDE = [
  'src',
  'scripts',
  'public/assets',
  'public/.well-known/security.txt',
  'package.json',
  'next.config.js',
  'vercel.json',
];

const SKIP_DIRS = new Set(['node_modules', '.next', '.git']);
// Generated by the signer; hashing them would make the digest self-referential.
const SKIP_FILES = new Set(['build-signature.json']);

function walk(abs, out) {
  let st;
  try {
    st = statSync(abs);
  } catch {
    return out;
  }
  if (st.isDirectory()) {
    for (const name of readdirSync(abs).sort()) {
      if (SKIP_DIRS.has(name)) continue;
      walk(join(abs, name), out);
    }
  } else if (st.isFile() && !SKIP_FILES.has(abs.split(sep).pop())) {
    out.push(abs);
  }
  return out;
}

/**
 * Digest of the source tree: sorted `sha256(content)  path` lines hashed
 * together. Deterministic across machines because paths are normalised to
 * forward slashes and the list is sorted before hashing.
 */
export function buildDigest(root) {
  const files = [];
  for (const entry of INCLUDE) walk(join(root, entry), files);

  const manifest = files
    .map((abs) => {
      const rel = relative(root, abs).split(sep).join('/');
      const hash = createHash('sha256').update(readFileSync(abs)).digest('hex');
      return `${hash}  ${rel}`;
    })
    .sort();

  return {
    manifest,
    digest: createHash('sha256').update(manifest.join('\n')).digest('hex'),
  };
}
